package app.recommandations;

import app.admin.Command;
import app.audioFiles.Song;
import app.users.artist.Artist;
import app.users.Host;
import app.users.user.User;
import com.fasterxml.jackson.databind.node.ObjectNode;

import java.util.ArrayList;
import java.util.Map;

public class RecommendationContext {
    private RecommendationStrategy strategy;

    /**
     * Sets the recommendation strategy.
     *
     * @param strategy The RecommendationStrategy to be set.
     */
    public void setStrategy(final RecommendationStrategy strategy) {
        this.strategy = strategy;
    }

    /**
     * Executes the current recommendation strategy.
     *
     * @param command The Command object containing user details and other relevant information.
     * @param users   Map of all users.
     * @param artists Map of all artists.
     * @param hosts   Map of all hosts.
     * @param songs   ArrayList of all available songs.
     * @return ObjectNode Result node generated by the recommendation strategy.
     */
    public ObjectNode executeStrategy(final Command command,
                                      final Map<String, User> users,
                                      final Map<String, Artist> artists,
                                      final Map<String, Host> hosts,
                                      final ArrayList<Song> songs) {
        return strategy.generateRecommendation(command, users, artists, hosts, songs);
    }

}
